name: Discord message
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Successful commit to https://github.com/{{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}.\n Diff: {{ github.context.payload.compare }}"
          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.githubusercontent.com/{{ commit.author.username }}"} }'
