name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize]

jobs:
  build_test_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: create env file
        run: |
          touch server/.env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_HOSTNAME=${{ secrets.DB_HOSTNAME }} >> .env
      - name: Install dependencies
        run: npm run install-app
      - name: lint checking
        run: npm run lint
        env:
          NODE_ENV: production
      - name: build
        run: npm run build-app
      - name: test
        run: npm run test-server
      # ****End to end Testing***** #
      # - name: e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
      - name: Deploy
        if: ${{ github.base_ref == 'main' }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "law-firm-management-sys" # Must be unique in Heroku
          heroku_email: "youneslamkhanter02@gmail.com"
          # healthcheck: "law-firm-management-sys.herokuapp.com/version"
          # checkString: "1.1.0"
      - name: Bump version and push tag
        if: ${{ github.base_ref == 'main' }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
